version: '3'
services:

  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: app-php
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network


  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    networks:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d
    networks:
      - app-network

  
  db:
    image: postgres
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: laravel_app
      POSTGRES_PASSWORD: my_password
      
    volumes:
      - ./dbdata:/var/lib/postgresql/ #dbdata:/var/lib/mysql/
      - ./postgres/my.cnf:/etc/postgresql/my.cnf #./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network
    
    

networks:
  app-network:
    driver: bridge

volumes:
    dbdata:
        driver: local
