pipeline {
    
  environment {
    registry = "hela98/laravelapp_images"
    registryCredential = 'docker_hub'
  
    DockerHub = credentials('docker_hub') 
  
    
  }
  agent any
  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }
    stage('Building image') {
      steps{
          
        sh "docker system prune"
        sh "docker-compose build"
        sh "docker-compose up -d"
      }
    }
    stage('Deploy Image') {
      steps{
            
            withCredentials([string(credentialsId:'docker_hub', variable: 'PASSWORD')]){
                sh "docker login -u hela98 -p ${PASSWORD}"
                sh "docker-compose push hela98/laravelapp_images:latest"
            }
      }
    }
    stage('Remove Unused docker image') {
      steps{
        sh "docker rmi -f $registry:latest"
      }
    }
    stage('Deploy to kBs'){
            steps{
                sh "chmod +x changeTag.sh" 
                sh"./changeTag.sh ${DOCKER_TAG}"
                sshagent (['hela-machine']){
                    sh "scp -o StrictHostKeyChecking=no services.yml laravel-app-pod.yml Hela@70.37.48.248:/home/Hela/"
      
                    script{
                        try{
                            sh "ssh Hela@70.37.48.248 kubectl apply -f"

                        }catch(error){
                            sh "ssh Hela@70.37.48.248 kubectl create -f."
                        }
                        
                    }
                }
            }
        }
    
  }
    
    
  }
    
